version: '3.7'

services:

  postgres-db-hjb-development:
    build:
      context: ./../../../../../../../databases/postgis
      dockerfile: ./postgres.Dockerfile
    image: postgres11-postgis2.5
    container_name: postgres-db-hjb-development
    command: postgres -c 'max_connections=10'
    volumes:
      - ./../../../../../../../data/postgres/data:/var/lib/postgresql/data
      - ./../../../../../../../data/postgres/backups:/opt/backups
    environment:
      - POSTGRES_DB=hjb-server-postgres-db
      - POSTGRES_USER=app_user
      - POSTGRES_PASSWORD=12345678
    ports:
      - 5444:5432
    networks:
      - test-postgis-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U app_user" ]
      interval: 10s
      timeout: 5s
      retries: 5


networks:
  test-postgis-network:
    name: test-postgis-network
    external: true
